spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    poolName: K.Geo.CP
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/k_party
    username: root
    #password:
    dbcp2:
      max-total: 1

swagger:
  version: "1.0"
  title: Party API
  description: Party API
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"

server:
  port: 8080

endpoints:
  enabled: true
  sensitive: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false

logging:
  level:
    root: INFO
    com.amazonaws: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF
    springfox: ERROR

  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"
